### ISSUE TITLE
report bug when validate on woz devset

### ISSUE THREAD

**Issue by SkyAndCloud** [SKTBrain/SUMBT#5]
Hi, I can't validate on woz devset after I updated recent commits. Here is the log:

```
Traceback (most recent call last):                                                                                                   
  File "code/main-multislot.py", line 1037, in <module>                                                                
  File "code/main-multislot.py", line 917, in main
    accuracies = eval_all_accs(pred_slot, label_ids, accuracies)
  File "code/main-multislot.py", line 1002, in eval_all_accs
    joint_acc, slot_acc, num_turn, num_data = _eval_acc(pred_slot[:,:,18:25], labels[:,:,18:25])
  File "code/main-multislot.py", line 985, in _eval_acc
    accuracy = (_pred_slot == _labels).view(-1, slot_dim)
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous
```

**Comment by libing125** [comment]
I saw the same error.

**Comment by zqwerty** [comment]
This code is for multiwoz, just comment out.
